import ReturnButton from "@/app/components/ReturnButton";
import { Metadata, ResolvingMetadata } from "next";

export async function generateMetadata(
    { params }: { params: { postName: string }}
): Promise<Metadata> {

    const postName = params.postName;

    return {
        title: postName.replaceAll("_", " "),
        description: "Generated by create next app"
    }
}

export default function BlogLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="w-full max-w-[600px] min-h-[calc(100vh-200px)] flex flex-1 flex-col items-center gap-[15px] p-[20px] mb-[50px]">
            <ReturnButton />
            { children }
        </div>
    );
}