import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import Header from './components/Header/Header';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: "--font-space-grotesk"
})

export const metadata: Metadata = {
  title: 'Wojciech Glid - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        <div className="sticky top-0 z-50 w-full flex justify-center border-b border-[#4850e612]" style={{ background: 'rgba(255,255,255,0.85)', backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)' }}>
          <Header />
        </div>
        { children }
        <footer className="w-full h-[100px] flex flex-col justify-center items-center gap-1 border-t border-[#4850e610]">
          <p className="text-xs text-[#7979b3]">© {new Date().getFullYear()} Wojciech Glid. All rights reserved.</p>
          <p className="text-[10px] text-[#7979b3] opacity-60 tracking-widest uppercase">Built with Next.js</p>
        </footer>
        <Analytics />
      </body>
    </html>
  )
}
